2018-07-29 00:55:06,733 - __main__ - INFO - insert into student_(sid,sname,sage,sgender,sphone)values
		('151310146','黄月英','34','女','13456658976')
2018-07-29 00:56:04,633 - __main__ - INFO - select * from student_
2018-07-29 00:56:54,254 - __main__ - INFO - select * from student_
2018-07-29 00:56:54,289 - __main__ - INFO - 打印了所有学生信息
2018-07-29 01:00:31,435 - __main__ - INFO - select * from student_
2018-07-29 01:00:31,460 - __main__ - INFO - 打印了所有学生信息
2018-07-29 01:08:49,709 - __main__ - INFO - select * from student_ where sid = 151310144
2018-07-29 01:08:59,669 - __main__ - INFO - select * from student_ where sid = 1513101111
2018-07-29 01:33:33,691 - __main__ - INFO - select * from student_
2018-07-29 01:33:33,697 - __main__ - INFO - 打印了所有学生信息
2018-07-29 02:48:17,135 - __main__ - INFO - select * from course_
2018-07-29 03:00:13,207 - __main__ - INFO - select * from course_
2018-07-29 03:02:08,636 - __main__ - INFO - insert into course_(cname, cstatu)values
		('Python','0')
2018-07-29 03:02:08,736 - __main__ - ERROR - Insert operation error
Traceback (most recent call last):
  File "mysql_logging.py", line 39, in insert
    cursor.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'cstatu' in 'field list'")
2018-07-29 03:04:01,499 - __main__ - INFO - insert into course_(cname, cstatus)values
		('Python','0')
2018-07-29 03:04:13,961 - __main__ - INFO - insert into course_(cname, cstatus)values
		('Java','0')
2018-07-29 03:04:57,087 - __main__ - INFO - insert into course_(cname, cstatus)values
		('Mysql','0')
2018-07-29 03:06:49,694 - __main__ - INFO - select * from course_
2018-07-29 03:08:03,046 - __main__ - INFO - select * from course_
2018-07-29 03:08:39,485 - __main__ - INFO - select * from course_
2018-07-29 03:09:12,421 - __main__ - INFO - select * from course_
2018-07-29 03:10:32,828 - __main__ - INFO - select * from course_
2018-07-29 03:11:13,900 - __main__ - INFO - select * from course_
2018-07-29 03:12:54,977 - __main__ - INFO - select * from course_
2018-07-29 03:13:17,165 - __main__ - INFO - insert into course_(cname, cstatus)values
		('Javascript','1')
2018-07-29 03:13:19,145 - __main__ - INFO - select * from course_
2018-07-29 03:13:42,184 - __main__ - INFO - select * from course_
2018-07-29 03:14:08,505 - __main__ - INFO - select * from course_
2018-07-29 03:14:26,802 - __main__ - INFO - select * from course_
2018-07-29 03:14:45,079 - __main__ - INFO - select * from course_
2018-07-29 03:15:01,400 - __main__ - INFO - select * from course_
2018-07-29 03:15:27,552 - __main__ - INFO - select * from course_
2018-07-29 03:24:32,642 - __main__ - INFO - select * from course_
2018-07-29 03:24:37,979 - __main__ - INFO - select * from course_
2018-07-29 03:24:49,835 - __main__ - INFO - select * from course_
2018-07-29 03:24:54,795 - __main__ - INFO - DELETE FROM course_ WHERE id = 4
2018-07-29 03:24:58,450 - __main__ - INFO - select * from course_
2018-07-29 03:37:04,279 - __main__ - INFO - select * from course_
2018-07-29 03:37:22,326 - __main__ - INFO - insert into course_(cname, cstatus)values
		('C#','1')
2018-07-29 03:37:24,494 - __main__ - INFO - select * from course_
2018-07-29 03:37:35,762 - __main__ - INFO - select * from course_
2018-07-29 03:38:09,008 - __main__ - INFO - select * from course_
2018-07-29 03:38:14,414 - __main__ - INFO - DELETE FROM course_ WHERE id = 4
2018-07-29 03:38:19,838 - __main__ - INFO - select * from course_
2018-07-29 03:39:46,950 - __main__ - INFO - select * from course_
2018-07-29 03:40:30,702 - __main__ - INFO - select * from course_
2018-07-29 03:40:47,711 - __main__ - INFO - select * from course_
2018-07-29 03:41:45,525 - __main__ - INFO - select * from course_
2018-07-29 03:42:55,886 - __main__ - INFO - select * from course_
2018-07-29 03:43:30,485 - __main__ - INFO - select * from course_
2018-07-29 03:43:39,215 - __main__ - INFO - update course_ set cname = Mysql, cstatus = 1 where id = 3
2018-07-29 03:43:39,288 - __main__ - ERROR - Search operation error
Traceback (most recent call last):
  File "mysql_logging.py", line 108, in update
    cur.execute(sql_update)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'Mysql' in 'field list'")
2018-07-29 03:45:14,994 - __main__ - INFO - select * from course_
2018-07-29 03:45:24,666 - __main__ - INFO - update course_ set cname = 'Mysql',cstatus = 1 where id = 3
2018-07-29 03:45:30,362 - __main__ - INFO - select * from course_
2018-07-29 03:45:43,275 - __main__ - INFO - update course_ set cname = 'javascript',cstatus = 1 where id = 4
2018-07-29 03:45:47,875 - __main__ - INFO - select * from course_
2018-07-29 04:08:29,253 - __main__ - INFO - select * from student_
2018-07-29 04:08:29,938 - __main__ - INFO - 打印了所有学生信息
2018-07-29 04:09:03,045 - __main__ - INFO - select * from student_
2018-07-29 04:09:03,433 - __main__ - INFO - 打印了所有学生信息
2018-07-29 04:09:38,861 - __main__ - INFO - select * from student_
2018-07-29 04:09:39,367 - __main__ - INFO - 打印了所有学生信息
2018-07-29 04:12:37,775 - __main__ - INFO - select * from student_
2018-07-29 04:12:37,862 - __main__ - INFO - 打印了所有学生信息
2018-07-29 04:13:21,054 - __main__ - INFO - select * from student_
2018-07-29 04:13:21,147 - __main__ - INFO - 打印了所有学生信息
2018-07-29 04:13:55,111 - __main__ - INFO - select * from student_
2018-07-29 04:13:55,226 - __main__ - INFO - 打印了所有学生信息
2018-07-29 04:14:23,640 - __main__ - INFO - update student_ set sid = 151310145,sname = '武则天',sage = 18, sgender = '女', sphone = 13867560980 where sid = 151310101
2018-07-29 04:14:34,796 - __main__ - INFO - select * from student_
2018-07-29 04:14:34,871 - __main__ - INFO - 打印了所有学生信息
2018-07-29 04:17:08,745 - __main__ - INFO - select * from course_
2018-07-29 04:17:55,449 - __main__ - INFO - select * from course_
2018-07-29 04:20:01,878 - __main__ - INFO - select * from course_
2018-07-29 04:20:07,902 - __main__ - INFO - select * from course_
2018-07-29 04:20:25,548 - __main__ - INFO - select * from course_
2018-07-29 04:27:36,040 - __main__ - INFO - select * from student_
2018-07-29 04:27:36,129 - __main__ - INFO - 打印了所有学生信息
2018-07-29 04:28:14,222 - __main__ - INFO - select * from student_
2018-07-29 04:28:14,339 - __main__ - INFO - 打印了所有学生信息
2018-07-29 04:28:43,885 - __main__ - INFO - select * from student_
2018-07-29 04:28:43,990 - __main__ - INFO - 打印了所有学生信息
2018-07-29 04:28:53,508 - __main__ - INFO - DELETE FROM student_ WHERE sid = 151310102
2018-07-29 04:28:58,396 - __main__ - INFO - select * from student_
2018-07-29 04:28:58,474 - __main__ - INFO - 打印了所有学生信息
2018-07-29 04:39:22,340 - mysql_logging - INFO - select * from student_
2018-07-29 04:39:51,068 - mysql_logging - INFO - select * from student_
2018-07-29 04:39:51,165 - __main__ - INFO - 打印了所有学生信息
2018-07-29 04:40:02,139 - mysql_logging - INFO - select * from course_
2018-07-29 04:40:09,716 - mysql_logging - INFO - select * from course_
2018-07-29 10:44:42,133 - logger - INFO - select * from student_
2018-07-29 10:44:43,000 - logger - INFO - 打印了所有学生信息
2018-07-29 10:45:42,768 - logger - INFO - select * from course_
2018-07-29 10:48:12,186 - logger - INFO - select * from student_
2018-07-29 10:48:12,191 - logger - INFO - 打印了所有学生信息
2018-07-29 12:35:02,804 - logger - INFO - select * from student_
2018-07-29 12:35:03,445 - logger - INFO - 打印了所有学生信息
2018-07-29 13:15:57,707 - logger - INFO - insert into user_(username, userpwd)values
		('151310107','151310107')
2018-07-29 13:33:59,668 - logger - INFO - select * from user_
2018-07-29 13:34:33,236 - logger - INFO - select * from user_
2018-07-29 13:34:49,365 - logger - INFO - select * from user_
2018-07-29 15:50:40,325 - logger - INFO - insert into user_(username, userpwd)values
		('151310107','151310107')
2018-07-29 15:50:40,407 - logger - ERROR - Insert operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 21, in insert
    cursor.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1364, "Field 'user_id' doesn't have a default value")
2018-07-29 15:51:35,308 - logger - INFO - insert into user_(username, userpwd)values
		('151310107','151310107')
2018-07-29 15:51:35,368 - logger - ERROR - Insert operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 21, in insert
    cursor.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1364, "Field 'user_id' doesn't have a default value")
2018-07-29 15:53:34,434 - logger - INFO - insert into user_(username, userpwd)values
		('151310107','151310107')
2018-07-29 15:53:44,100 - logger - INFO - select * from user_
2018-07-29 15:53:56,332 - logger - INFO - select * from user_
2018-07-29 15:54:38,624 - logger - INFO - insert into student_(sid,sname,sage,sgender,sphone)values
		('151310107','李白','18','男','13564685456')
2018-07-29 15:54:38,658 - logger - INFO - insert into user_ (stu_id) values (user) where username = user
2018-07-29 15:54:38,679 - logger - ERROR - Insert operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 21, in insert
    cursor.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where username = user' at line 1")
2018-07-29 16:02:54,339 - logger - INFO - select * from user_
2018-07-29 16:03:48,737 - logger - INFO - insert into student_(sid,sname,sage,sgender,sphone)values
		('151310107','李小白','18','男','13354684554')
2018-07-29 16:03:48,809 - logger - INFO - update usr_ set stu_id = 151310107,where username = 151310107
2018-07-29 16:03:48,919 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 75, in update
    cur.execute(sql_update)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where username = 151310107' at line 1")
2018-07-29 16:06:48,266 - logger - INFO - select * from user_
2018-07-29 16:07:16,853 - logger - INFO - insert into student_(sid,sname,sage,sgender,sphone)values
		('151310123','礼拜','14','男','12345437896')
2018-07-29 16:07:16,886 - logger - INFO - update usr_ set stu_id = 151310123, where username == 151310107
2018-07-29 16:07:16,934 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 75, in update
    cur.execute(sql_update)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where username == 151310107' at line 1")
2018-07-29 16:10:28,648 - logger - INFO - select * from user_
2018-07-29 16:10:54,569 - logger - INFO - insert into student_(sid,sname,sage,sgender,sphone)values
		('151310107','礼拜','14','男','13371913706')
2018-07-29 16:10:54,641 - logger - INFO - update user_ set stu_id = 151310107, where username = 151310107
2018-07-29 16:10:54,663 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 75, in update
    cur.execute(sql_update)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where username = 151310107' at line 1")
2018-07-29 16:13:44,806 - logger - INFO - select * from user_
2018-07-29 16:14:05,918 - logger - INFO - insert into student_(sid,sname,sage,sgender,sphone)values
		('151310108','礼拜','14','男','12278787878')
2018-07-29 16:14:05,975 - logger - INFO - update user_ set stu_id = '151310108', where username = '151310108'
2018-07-29 16:14:06,010 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 75, in update
    cur.execute(sql_update)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where username = '151310108'' at line 1")
2018-07-29 16:16:59,597 - logger - INFO - select * from user_
2018-07-29 16:17:23,103 - logger - INFO - insert into student_(sid,sname,sage,sgender,sphone)values
		('13','也起','12','男','12234336789')
2018-07-29 16:17:23,157 - logger - INFO - update user_ set stu_id = '13', where username = 151310107
2018-07-29 16:17:23,211 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 75, in update
    cur.execute(sql_update)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where username = 151310107' at line 1")
2018-07-29 16:23:19,722 - logger - INFO - select * from user_
2018-07-29 16:23:38,858 - logger - INFO - select * from user_
2018-07-29 16:23:59,511 - logger - INFO - insert into student_(sid,sname,sage,sgender,sphone)values
		('151310107','礼拜','13','男','1443625136')
2018-07-29 16:23:59,552 - logger - INFO - update user_ set stu_id = '151310107', where username = 151310107
2018-07-29 16:23:59,597 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 75, in update
    cur.execute(sql_update)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where username = 151310107' at line 1")
2018-07-29 16:29:17,442 - logger - INFO - select * from student_
2018-07-29 16:29:17,534 - logger - INFO - 打印了所有学生信息
2018-07-29 16:29:50,433 - logger - INFO - update student_ set sid = 151310105,sname = 'asd',sage = 23, sgender = 'nan ', sphone = 12313 where sid = 13
2018-07-29 16:31:35,921 - logger - INFO - select * from user_
2018-07-29 16:32:00,467 - logger - INFO - insert into student_(sid,sname,sage,sgender,sphone)values
		('151310199','吕布','28','男','13371898976')
2018-07-29 16:32:00,538 - logger - INFO - update user_ set stu_id = '151310199'where username = 151310107
2018-07-29 16:40:59,844 - logger - INFO - select * from user_
2018-07-29 16:41:04,072 - logger - INFO - select * from student_ where user_.stu_id =151310107
2018-07-29 16:41:04,152 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 39, in search
    cur.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'user_.stu_id' in 'where clause'")
2018-07-29 16:50:17,493 - logger - INFO - select * from user_
2018-07-29 16:50:23,436 - logger - INFO - SELECT student_.sname,student_.gender FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 16:50:23,544 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 39, in search
    cur.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'student_.gender' in 'field list'")
2018-07-29 16:50:46,325 - logger - INFO - select * from user_
2018-07-29 16:50:49,942 - logger - INFO - SELECT student_.sname,student_.sgender FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:09:14,761 - logger - INFO - select * from user_
2018-07-29 18:09:18,249 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.age, student_.phone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:09:18,392 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 39, in search
    cur.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'student_.age' in 'field list'")
2018-07-29 18:09:52,984 - logger - INFO - select * from user_
2018-07-29 18:09:55,528 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:10:53,947 - logger - INFO - select * from user_
2018-07-29 18:10:58,345 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:11:39,246 - logger - INFO - select * from user_
2018-07-29 18:11:42,118 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:13:04,372 - logger - INFO - select * from user_
2018-07-29 18:13:06,684 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:14:11,219 - logger - INFO - select * from user_
2018-07-29 18:14:13,226 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:15:42,944 - logger - INFO - select * from user_
2018-07-29 18:15:53,816 - logger - INFO - select * from user_
2018-07-29 18:15:55,512 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:17:26,934 - logger - INFO - select * from user_
2018-07-29 18:17:29,134 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:19:34,539 - logger - INFO - select * from user_
2018-07-29 18:19:37,515 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:19:56,530 - logger - INFO - select * from user_
2018-07-29 18:19:59,123 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:21:05,585 - logger - INFO - select * from user_
2018-07-29 18:21:07,185 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:21:41,121 - logger - INFO - select * from user_
2018-07-29 18:21:42,329 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:31:04,310 - logger - INFO - select * from student_
2018-07-29 18:31:04,389 - logger - INFO - 打印了所有学生信息
2018-07-29 18:32:00,381 - logger - INFO - update student_ set sid = 151310199,sname = '',sage = 55, sgender = '男', sphone = 131345567890 where sid = 151310199
2018-07-29 18:32:18,821 - logger - INFO - select * from user_
2018-07-29 18:32:21,437 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:33:29,334 - logger - INFO - insert into student_(sid,sname,sage,sgender,sphone)values
		('151310107','叶强','21','男','13371913706')
2018-07-29 18:33:29,492 - logger - INFO - update user_ set stu_id = '151310107'where username = 151310107
2018-07-29 18:33:32,475 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:33:40,883 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:35:28,358 - logger - INFO - select * from user_
2018-07-29 18:35:56,624 - logger - INFO - insert into student_(sid,sname,sage,sgender,sphone)values
		('151310108','林','23','男','1233434334')
2018-07-29 18:35:56,683 - logger - INFO - update user_ set stu_id = '151310108'where username = 151310107
2018-07-29 18:35:59,944 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:39:03,006 - logger - INFO - select * from user_
2018-07-29 18:45:40,895 - logger - INFO - insert into student_(sid,sname,sage,sgender,sphone)values
		('151310222','李逵','34','男','13376768998')
2018-07-29 18:45:43,257 - logger - INFO - insert into user_(username, userpwd, stu_id)values
		('python','python','151310222')
2018-07-29 18:45:56,738 - logger - INFO - select * from user_
2018-07-29 18:46:01,347 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:46:17,710 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:46:18,534 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:48:01,828 - logger - INFO - select * from user_
2018-07-29 18:48:04,253 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:51:59,441 - logger - INFO - python
2018-07-29 18:51:59,442 - logger - INFO - select * from user_
2018-07-29 18:52:03,170 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:56:03,824 - logger - INFO - select * from user_
2018-07-29 18:56:05,864 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:57:15,547 - logger - INFO - select * from user_
2018-07-29 18:57:17,148 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid
2018-07-29 18:59:26,599 - logger - INFO - select * from user_
2018-07-29 18:59:32,823 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = python
2018-07-29 18:59:32,878 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 39, in search
    cur.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'python' in 'where clause'")
2018-07-29 19:01:44,682 - logger - INFO - select * from user_
2018-07-29 19:01:49,194 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:01:52,842 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:02:05,113 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:02:05,174 - logger - INFO - select * from course_
2018-07-29 19:03:45,567 - logger - INFO - select * from user_
2018-07-29 19:04:28,077 - logger - INFO - insert into student_(sid,sname,sage,sgender,sphone)values
		('151310123','宋江','45','男','15786789084')
2018-07-29 19:04:30,194 - logger - INFO - insert into user_(username, userpwd, stu_id)values
		('mysql','mysql','151310123')
2018-07-29 19:04:37,198 - logger - INFO - select * from user_
2018-07-29 19:04:39,974 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'mysql'
2018-07-29 19:07:25,517 - logger - INFO - select * from user_
2018-07-29 19:07:28,765 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:07:31,052 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:07:31,056 - logger - INFO - select * from student_
2018-07-29 19:07:31,104 - logger - INFO - 打印了所有学生信息
2018-07-29 19:13:15,870 - logger - INFO - select * from user_
2018-07-29 19:13:20,390 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:13:23,270 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:14:31,800 - logger - INFO - select * from user_
2018-07-29 19:14:35,608 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:14:38,079 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:15:19,488 - logger - INFO - update student_ set sid = 151310222,sname = '李旋风',sage = 34, sgender = '男', sphone = 13376784352 where sid = 151310222
2018-07-29 19:15:21,304 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:17:32,490 - logger - INFO - select * from user_
2018-07-29 19:17:35,914 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:17:37,674 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:18:24,211 - logger - INFO - update student_ sname = '（黑旋风）',sage = 34, sgender = '男', sphone = 13376784352 where sid = 151310222
2018-07-29 19:18:24,315 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 75, in update
    cur.execute(sql_update)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= '（黑旋风）',sage = 34, sgender = '男', sphone = 13376784352 where sid =' at line 1")
2018-07-29 19:20:50,288 - logger - INFO - select * from user_
2018-07-29 19:20:58,014 - logger - INFO - select * from user_
2018-07-29 19:20:59,974 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:21:02,134 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:21:25,103 - logger - INFO - update student_ sname = '李逵',sage = 34, sgender = '男', sphone = 13376789807 where sid = 151310222
2018-07-29 19:21:25,157 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 75, in update
    cur.execute(sql_update)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= '李逵',sage = 34, sgender = '男', sphone = 13376789807 where sid = 15131022' at line 1")
2018-07-29 19:24:47,219 - logger - INFO - select * from user_
2018-07-29 19:24:53,779 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:24:55,675 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:25:20,716 - logger - INFO - update student_ sname = '李逵',sage = 34, sgender = '男', sphone = 13676768888 where sid = 151310222
2018-07-29 19:25:20,790 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 75, in update
    cur.execute(sql_update)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= '李逵',sage = 34, sgender = '男', sphone = 13676768888 where sid = 15131022' at line 1")
2018-07-29 19:27:57,416 - logger - INFO - select * from user_
2018-07-29 19:28:05,031 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:28:07,079 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:28:25,680 - logger - INFO - update student_ sname = '李逵',sage = 34, sgender = '男', sphone = 13344545656 where sid = '151310222'
2018-07-29 19:28:25,752 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 75, in update
    cur.execute(sql_update)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= '李逵',sage = 34, sgender = '男', sphone = 13344545656 where sid = '1513102' at line 1")
2018-07-29 19:33:14,943 - logger - INFO - select * from user_
2018-07-29 19:33:18,320 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:33:20,487 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:33:41,411 - logger - INFO - update student_ sname = 李逵, sage = 14,sgender = 男, sphone=12334343455 where sid = 151310222
2018-07-29 19:33:41,490 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 75, in update
    cur.execute(sql_update)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= 李逵, sage = 14,sgender = 男, sphone=12334343455 where sid = 151310222' at line 1")
2018-07-29 19:38:05,876 - logger - INFO - select * from user_
2018-07-29 19:38:07,076 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:38:08,291 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:38:20,786 - logger - INFO - update student_ sname = '1',sage = 1, sgender = '1', sphone = 1 where sid = '151310222'
2018-07-29 19:38:20,865 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 75, in update
    cur.execute(sql_update)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= '1',sage = 1, sgender = '1', sphone = 1 where sid = '151310222'' at line 1")
2018-07-29 19:39:00,510 - logger - INFO - select * from user_
2018-07-29 19:39:08,781 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:39:10,101 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:39:20,460 - logger - INFO - update student_ sname = 'liky',sage = 34, sgender = 'nan', sphone = 12313 where sid = '151310222'
2018-07-29 19:39:20,549 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 75, in update
    cur.execute(sql_update)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= 'liky',sage = 34, sgender = 'nan', sphone = 12313 where sid = '151310222'' at line 1")
2018-07-29 19:43:08,733 - logger - INFO - select * from user_
2018-07-29 19:43:11,530 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-29 19:43:31,793 - logger - INFO - update student_ set sname = '李逵',sage = 34, sgender = '男', sphone = 15378690087 where sid = '151310222'
2018-07-29 19:43:35,108 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 00:09:53,139 - logger - INFO - select * from user_
2018-07-30 00:09:57,057 - logger - INFO - select * from course_
2018-07-30 00:11:40,301 - logger - INFO - select * from user_
2018-07-30 00:11:42,744 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 00:13:21,048 - logger - INFO - select * from user_
2018-07-30 00:13:23,249 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 00:13:25,168 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 00:13:39,219 - logger - INFO - select * from user_
2018-07-30 00:13:40,722 - logger - INFO - select * from course_
2018-07-30 00:13:45,416 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 00:20:38,341 - logger - INFO - select * from user_
2018-07-30 00:20:45,278 - logger - INFO - select * from user_
2018-07-30 00:20:50,349 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 00:20:55,814 - logger - INFO - select * from course_
2018-07-30 00:20:58,183 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 00:20:58,234 - logger - INFO - insert into stu2course(sid, cid)values(41,5)
2018-07-30 00:33:21,419 - logger - INFO - select * from user_
2018-07-30 00:33:24,452 - logger - INFO - select * from student_ inner join stu2course on student_.id=stu2course.id 
		inner join course_ on course_.id=stu2course.id
2018-07-30 00:33:24,583 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 39, in search
    cur.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'stu2course.id' in 'on clause'")
2018-07-30 00:34:33,734 - logger - INFO - select * from user_
2018-07-30 00:34:35,621 - logger - INFO - select * from student_ inner join stu2course on student_.id=stu2course.sid 
		inner join course_ on course_.id=stu2course.cid
2018-07-30 00:37:22,107 - logger - INFO - select * from user_
2018-07-30 00:37:27,155 - logger - INFO - select * from course_
2018-07-30 00:37:30,154 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 00:37:30,222 - logger - INFO - insert into stu2course(sid, cid)values(41,3)
2018-07-30 00:37:34,874 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid 
		inner join course_ on course_.id=stu2course.cid
2018-07-30 00:39:35,449 - logger - INFO - select * from student_
2018-07-30 00:39:35,646 - logger - INFO - 打印了所有学生信息
2018-07-30 00:39:48,412 - logger - INFO - select * from student_ where sname = '礼拜'
2018-07-30 00:40:21,565 - logger - INFO - select * from student_ where sid = 151310107
2018-07-30 00:40:41,901 - logger - INFO - select * from student_
2018-07-30 00:40:41,982 - logger - INFO - 打印了所有学生信息
2018-07-30 00:40:57,095 - logger - INFO - select * from student_
2018-07-30 00:40:57,176 - logger - INFO - 打印了所有学生信息
2018-07-30 00:41:07,208 - logger - INFO - DELETE FROM student_ WHERE sid = 151310199
2018-07-30 00:41:15,934 - logger - INFO - select * from student_
2018-07-30 00:41:15,994 - logger - INFO - 打印了所有学生信息
2018-07-30 00:41:28,158 - logger - INFO - select * from course_
2018-07-30 00:41:35,098 - logger - INFO - select * from course_
2018-07-30 00:42:07,671 - logger - INFO - select * from course_
2018-07-30 00:44:08,512 - logger - INFO - select * from user_
2018-07-30 00:44:11,784 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = '151310107'
2018-07-30 00:44:17,697 - logger - INFO - select * from course_
2018-07-30 00:44:19,591 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = '151310107'
2018-07-30 00:44:19,602 - logger - INFO - insert into stu2course(sid, cid)values(35,1)
2018-07-30 00:44:20,537 - logger - INFO - select * from course_
2018-07-30 00:44:22,953 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = '151310107'
2018-07-30 00:44:22,962 - logger - INFO - insert into stu2course(sid, cid)values(35,1)
2018-07-30 00:44:23,047 - logger - ERROR - Insert operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 21, in insert
    cursor.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '35-1' for key 'PRIMARY'")
2018-07-30 00:45:03,288 - logger - INFO - select * from user_
2018-07-30 00:45:05,681 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid 
		inner join course_ on course_.id=stu2course.cid
2018-07-30 00:45:25,993 - logger - INFO - select * from course_
2018-07-30 00:45:26,155 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = '151310107'
2018-07-30 00:47:01,199 - logger - INFO - select * from user_
2018-07-30 00:47:06,489 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 00:47:14,033 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid 
		inner join course_ on course_.id=stu2course.cid
2018-07-30 00:47:22,946 - logger - INFO - select * from course_
2018-07-30 00:47:24,802 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 00:47:24,884 - logger - INFO - insert into stu2course(sid, cid)values(41,1)
2018-07-30 00:47:27,842 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid 
		inner join course_ on course_.id=stu2course.cid
2018-07-30 13:25:09,895 - logger - INFO - select * from user_
2018-07-30 13:25:15,424 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = '151310107'
2018-07-30 13:25:20,943 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = '151310107'
2018-07-30 13:25:48,040 - logger - INFO - update student_ set sname = 'test',sage = 13, sgender = '男', sphone = 13376768789 where sid = '151310108'
2018-07-30 13:25:52,032 - logger - INFO - select * from course_
2018-07-30 13:25:53,560 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = '151310107'
2018-07-30 13:25:53,603 - logger - INFO - insert into stu2course(sid, cid)values(35,1)
2018-07-30 13:25:53,755 - logger - ERROR - Insert operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 21, in insert
    cursor.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '35-1' for key 'PRIMARY'")
2018-07-30 13:36:01,179 - logger - INFO - select * from user_
2018-07-30 13:36:05,549 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 13:36:10,251 - logger - INFO - select * from course_
2018-07-30 13:36:11,701 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 13:36:11,731 - logger - INFO - insert into stu2course(sid, cid)values(41,1)
2018-07-30 13:36:11,738 - logger - ERROR - Insert operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 21, in insert
    cursor.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '41-1' for key 'PRIMARY'")
2018-07-30 13:37:23,053 - logger - INFO - select * from user_
2018-07-30 13:37:28,798 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid 
		inner join course_ on course_.id=stu2course.cid
2018-07-30 13:37:42,066 - logger - INFO - select * from course_
2018-07-30 13:37:45,012 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 13:37:45,072 - logger - INFO - insert into stu2course(sid, cid)values(41,2)
2018-07-30 14:30:43,534 - logger - INFO - select * from user_
2018-07-30 14:30:46,065 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid 
		inner join course_ on course_.id=stu2course.cid
		inner join user_ on user_.stu_id = student_.sid 
		 
2018-07-30 14:35:42,365 - logger - INFO - select * from user_
2018-07-30 14:35:47,375 - logger - INFO - select * from user_
2018-07-30 14:38:18,431 - logger - INFO - select * from user_
2018-07-30 14:38:22,382 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid 
		inner join course_ on course_.id=stu2course.cid
		inner join user_ on user_.username = python 
		 
2018-07-30 14:38:22,710 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 39, in search
    cur.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'python' in 'on clause'")
2018-07-30 14:41:18,233 - logger - INFO - select * from user_
2018-07-30 14:41:20,885 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 14:41:21,023 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid 
		inner join course_ on course_.id=stu2course.cid
		where student_.stu_id = 41
		 
2018-07-30 14:41:21,039 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 39, in search
    cur.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'student_.stu_id' in 'where clause'")
2018-07-30 14:42:46,708 - logger - INFO - select * from user_
2018-07-30 14:42:48,156 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 14:42:48,184 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid 
		inner join course_ on course_.id=stu2course.cid
		where student_.sid = 41
		 
2018-07-30 14:44:13,947 - logger - INFO - select * from user_
2018-07-30 14:44:15,843 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 14:44:15,898 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 41
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 14:44:22,024 - logger - INFO - select * from course_
2018-07-30 14:44:24,532 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 14:44:24,597 - logger - INFO - insert into stu2course(sid, cid)values(41,1)
2018-07-30 14:44:24,623 - logger - ERROR - Insert operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 21, in insert
    cursor.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '41-1' for key 'PRIMARY'")
2018-07-30 14:46:41,159 - logger - INFO - select * from user_
2018-07-30 14:46:46,510 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 14:46:46,616 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid 
		inner join course_ on course_.id=stu2course.cid
		inner join user_ on user_.sid = 41
		 
2018-07-30 14:46:46,650 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 39, in search
    cur.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'user_.sid' in 'on clause'")
2018-07-30 14:47:35,383 - logger - INFO - select * from user_
2018-07-30 14:47:37,113 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 14:47:37,204 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid 
		inner join course_ on course_.id=stu2course.cid
		inner join user_ on user_.stu_id = 41
		 
2018-07-30 14:48:43,937 - logger - INFO - select * from user_
2018-07-30 14:48:45,171 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 14:48:45,276 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid 
		inner join course_ on course_.id=stu2course.cid
		inner join user_ on user_.stu_id = 151310222
		 
2018-07-30 14:48:59,474 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 14:49:06,868 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 14:49:06,929 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid 
		inner join course_ on course_.id=stu2course.cid
		inner join user_ on user_.stu_id = 151310222
		 
2018-07-30 14:50:01,101 - logger - INFO - select * from user_
2018-07-30 14:50:04,355 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 14:50:04,410 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310222
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 14:59:01,422 - logger - INFO - select * from user_
2018-07-30 14:59:03,512 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 14:59:03,555 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310222
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 14:59:21,249 - logger - INFO - select * from user_
2018-07-30 14:59:23,273 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = '151310107'
2018-07-30 14:59:23,277 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310108
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 14:59:29,616 - logger - INFO - select * from course_
2018-07-30 14:59:31,385 - logger - INFO - SELECT  151310107 FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = student_.id
2018-07-30 14:59:56,862 - logger - INFO - select * from user_
2018-07-30 14:59:59,563 - logger - INFO - select * from course_
2018-07-30 15:00:01,138 - logger - INFO - SELECT  151310107 FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = student_.id
2018-07-30 15:01:40,105 - logger - INFO - select * from user_
2018-07-30 15:01:41,520 - logger - INFO - select * from course_
2018-07-30 15:01:42,444 - logger - INFO - SELECT  151310107 FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = student_.id
2018-07-30 15:03:15,352 - logger - INFO - select * from user_
2018-07-30 15:03:27,826 - logger - INFO - select * from user_
2018-07-30 15:03:31,155 - logger - INFO - select * from course_
2018-07-30 15:03:32,836 - logger - INFO - SELECT  student_.id FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 151310107
2018-07-30 15:03:32,943 - logger - INFO - insert into stu2course(sid, cid)values(35,2)
2018-07-30 15:03:43,616 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = '151310107'
2018-07-30 15:03:43,709 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310108
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 15:03:53,237 - logger - INFO - select * from course_
2018-07-30 15:03:55,328 - logger - INFO - SELECT  student_.id FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 151310107
2018-07-30 15:03:55,402 - logger - INFO - insert into stu2course(sid, cid)values(35,5)
2018-07-30 15:03:58,387 - logger - INFO - select * from course_
2018-07-30 15:04:00,126 - logger - INFO - SELECT  student_.id FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 151310107
2018-07-30 15:04:00,183 - logger - INFO - insert into stu2course(sid, cid)values(35,3)
2018-07-30 15:04:03,417 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = '151310107'
2018-07-30 15:04:03,478 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310108
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 15:04:09,383 - logger - INFO - select * from course_
2018-07-30 15:04:10,784 - logger - INFO - SELECT  student_.id FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 151310107
2018-07-30 15:04:10,846 - logger - INFO - insert into stu2course(sid, cid)values(35,1)
2018-07-30 15:04:10,848 - logger - ERROR - Insert operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 21, in insert
    cursor.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '35-1' for key 'PRIMARY'")
2018-07-30 15:07:04,173 - logger - INFO - select * from user_
2018-07-30 15:07:05,990 - logger - INFO - SELECT  student_.sid FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = python
2018-07-30 15:07:06,052 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 56, in searchOne
    cur.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'python' in 'where clause'")
2018-07-30 15:13:42,630 - logger - INFO - select * from user_
2018-07-30 15:13:47,043 - logger - INFO - SELECT  student_.id FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = python
2018-07-30 15:13:47,130 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 56, in searchOne
    cur.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'python' in 'where clause'")
2018-07-30 15:15:41,328 - logger - INFO - select * from user_
2018-07-30 15:15:43,763 - logger - INFO - SELECT  student_.id FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 151310107
2018-07-30 15:15:43,763 - logger - INFO - SELECT  student_.id FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 151310107
2018-07-30 15:15:43,928 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 35 
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 15:15:56,195 - logger - INFO - SELECT  student_.id FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 151310107
2018-07-30 15:15:56,196 - logger - INFO - SELECT  student_.id FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 151310107
2018-07-30 15:15:56,261 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 35 
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 15:16:08,574 - logger - INFO - select * from user_
2018-07-30 15:16:09,610 - logger - INFO - SELECT  student_.id FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = python
2018-07-30 15:16:09,610 - logger - INFO - SELECT  student_.id FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = python
2018-07-30 15:16:09,646 - logger - ERROR - Search operation error
Traceback (most recent call last):
  File "/home/python/Desktop/LearnPython/Student/StudentByMysql/Db.py", line 56, in searchOne
    cur.execute(sql)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.5/dist-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'python' in 'where clause'")
2018-07-30 15:22:11,324 - logger - INFO - select * from user_
2018-07-30 15:22:12,690 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 15:22:12,765 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310222
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 15:24:32,456 - logger - INFO - select * from user_
2018-07-30 15:24:33,814 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 15:24:33,871 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310222
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 15:25:19,836 - logger - INFO - select * from user_
2018-07-30 15:25:24,949 - logger - INFO - select * from user_
2018-07-30 15:25:29,333 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'mysql'
2018-07-30 15:25:33,934 - logger - INFO - select * from course_
2018-07-30 15:25:34,941 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'mysql'
2018-07-30 15:25:34,988 - logger - INFO - insert into stu2course(sid, cid)values(33,1)
2018-07-30 15:25:36,732 - logger - INFO - select * from course_
2018-07-30 15:25:39,418 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'mysql'
2018-07-30 15:25:39,500 - logger - INFO - insert into stu2course(sid, cid)values(33,2)
2018-07-30 15:25:41,059 - logger - INFO - select * from course_
2018-07-30 15:25:42,279 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'mysql'
2018-07-30 15:25:42,425 - logger - INFO - insert into stu2course(sid, cid)values(33,3)
2018-07-30 15:25:47,326 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'mysql'
2018-07-30 15:25:47,475 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310123
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 15:35:25,083 - logger - INFO - select * from user_
2018-07-30 15:35:26,885 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 15:35:26,927 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310222
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 15:39:39,100 - logger - INFO - insert into student_(sid,sname,sage,sgender,sphone)values
		('151310188','司马相如','67','男','15677678888')
2018-07-30 15:39:39,171 - logger - INFO - insert into user_(username, userpwd, stu_id)values
		('java','java','151310188')
2018-07-30 15:39:46,507 - logger - INFO - select * from user_
2018-07-30 15:39:49,383 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'java'
2018-07-30 15:39:53,813 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'java'
2018-07-30 15:39:53,867 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310188
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 15:41:01,727 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'java'
2018-07-30 15:41:01,826 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310188
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 15:41:06,106 - logger - INFO - select * from course_
2018-07-30 15:41:08,751 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'java'
2018-07-30 15:41:08,912 - logger - INFO - insert into stu2course(sid, cid)values(43,1)
2018-07-30 15:41:25,685 - logger - INFO - select * from user_
2018-07-30 15:41:29,853 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'java'
2018-07-30 15:41:30,604 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310188
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 15:41:34,456 - logger - INFO - select * from course_
2018-07-30 15:41:36,554 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'java'
2018-07-30 15:41:36,623 - logger - INFO - insert into stu2course(sid, cid)values(43,5)
2018-07-30 15:41:38,450 - logger - INFO - select * from course_
2018-07-30 15:41:42,467 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'java'
2018-07-30 15:41:42,569 - logger - INFO - insert into stu2course(sid, cid)values(43,3)
2018-07-30 15:41:47,276 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'java'
2018-07-30 15:41:47,319 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310188
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 15:42:09,255 - logger - INFO - select * from user_
2018-07-30 15:42:28,969 - logger - INFO - select * from student_
2018-07-30 15:42:29,052 - logger - INFO - 打印了所有学生信息
2018-07-30 15:42:38,243 - logger - INFO - select * from course_
2018-07-30 15:42:53,191 - logger - INFO - insert into course_(cname, cstatus)values
		('javascript','0')
2018-07-30 15:43:05,088 - logger - INFO - insert into course_(cname, cstatus)values
		('ruby','0')
2018-07-30 15:43:09,819 - logger - INFO - select * from course_
2018-07-30 15:43:32,519 - logger - INFO - select * from user_
2018-07-30 15:43:36,734 - logger - INFO - SELECT student_.sid,student_.sname,student_.sgender,student_.sage, student_.sphone FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 15:43:51,950 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 15:43:51,989 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310222
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 15:43:53,481 - logger - INFO - select * from course_
2018-07-30 15:43:58,497 - logger - INFO - SELECT student_.id  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 15:43:58,543 - logger - INFO - insert into stu2course(sid, cid)values(41,7)
2018-07-30 15:44:00,872 - logger - INFO - SELECT student_.sid  FROM student_,user_ WHERE user_.stu_id=student_.sid and user_.username = 'python'
2018-07-30 15:44:00,876 - logger - INFO - select student_.sname, student_.sage, student_.sgender, course_.cname, course_.cstatus from student_ inner join stu2course on student_.id=stu2course.sid and student_.sid = 151310222
		inner join course_ on course_.id=stu2course.cid
		 
2018-07-30 15:48:46,140 - logger - INFO - select * from user_
2018-07-30 15:50:11,084 - logger - INFO - select * from user_
2018-07-30 15:51:03,746 - logger - INFO - select * from user_
2018-07-30 15:51:42,423 - logger - INFO - select * from user_
2018-07-30 15:56:47,443 - logger - INFO - select * from user_
2018-07-30 15:58:02,084 - logger - INFO - select * from user_
